In [1]:
import pandas as pd
import numpy as np
from pandas.tools.plotting import scatter_matrix
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
# Do features really care if they fall under category 'note count' or 'step count'? 
# i.e. should I treat them all as equal? And not nested under my two high-level feature groups

# Should interval between notes be calculated as below too, or by 'DictVectorizer'?

In [29]:
#DOESN'T RECOGNIZE VOCABULARY WHEN CORPUS CONSISTS OF ONLY 1-2 LETTER 'WORDS'
# Must define token_pattern using a regex

#CASE 1: doesn't work
notes_corpus = ['A B C D', 'A# B- C D E-', 'A C A E-']

#CASE 2: doesn't work
# notes_corpus = ['A# B- C# D-', 'A# B- D- E-', 'A- C# A- E-']

#CASE 3: works
# notes_corpus = ['noteA noteB noteC noteD', 'noteA# noteB- noteC noteD noteE-', 'noteA noteC noteA noteE-']

# vocab = ['A-', 'A', 'A#', 'B-', 'B', 'C', '#C', 'D-', 'D', 'D#', 'E-', 'E', 'F', "F#", 'G-', 'G', 'G#']
note_vectorizer = TfidfVectorizer(stop_words=None, min_df=1, analyzer='word', token_pattern=r'\w#?-?')

# # Test to see if analyzer + token_pattern are working... :(
analyze = note_vectorizer.build_analyzer()
analyze('A B- C') == (['A', 'B-', 'C'])

print note_vectorizer.fit_transform(notes_corpus).todense()

[[ 0.4804584   0.          0.63174505  0.          0.37311881  0.4804584
   0.        ]
 [ 0.          0.53409337  0.          0.53409337  0.31544415  0.40619178
   0.40619178]
 [ 0.84492112  0.          0.          0.          0.32807831  0.
   0.42246056]]


In [25]:
step_corpus = ['2 4 2 1 1', '4 2 1 2 3 3', '2 1 1 2', '3 2 1 1 4']
step_vectorizer = TfidfVectorizer(stop_words=None, min_df=1, analyzer='word', token_pattern=r'\d\d?')
print step_vectorizer.fit_transform(step_corpus).todense()

[[ 0.6490196   0.6490196   0.          0.39692207]
 [ 0.25297042  0.50594085  0.7643884   0.30941914]
 [ 0.70710678  0.70710678  0.          0.        ]
 [ 0.67501827  0.33750914  0.50991745  0.41282212]]
